### ISSUE TITLE
Allow higher resolution of timestamps in JSON logging

### ISSUE THREAD

**Issue by knutwannheden** [dmlloyd/jboss-logmanager-embedded#7]
Note: I am using this module through Quarkus and am a little bit unsure whether to file this ticket against Quarkus or here. But since I don't see any easy way for Quarkus to address this, I felt it was best to file the issue here.

In my Quarkus application I use the `logging-json` extension to log the messages in JSON. Now I would like the timestamps in the log messages to have a higher resolution that milliseconds (in my case I would like to have microseconds, but higher would also be OK). First I thought I would be able to solve this by setting `quarkus.log.console.json.date-format`, but this has two problems:
- The config only allows me to specify a stringified pattern, where I wouldn't be able to express the standard ISO date-time pattern, but with microsecond precision, since the character `T` is reserved, so the formatter would have to be constructed using a `DateTimeFormatterBuilder`.
  - As I already said, higher precision would also work for me and the standard ISO pattern actually already has nanosecond precision, so this isn't really a problem and further it would be Quarkus-specific anyway.
- `StructuredFormatter#format()` unfortunately only keeps the milliseconds from the log record's timestamp: https://github.com/dmlloyd/jboss-logmanager-embedded/blob/4dd79e9d8970b71bad78f66fd2849e5479e48701/src/main/java/org/jboss/logmanager/formatters/StructuredFormatter.java#L209

I am not quite sure what change to propose here. If `dateTimeFormatter.format(Instant.ofEpochMilli(record.getMillis()))` were to be changed to `dateTimeFormatter.format(record.getInstant())` then my problem would be solved, but then other users may start complaining, since the timestamps now sometimes have higher precision (the formatter will only append as many fractional seconds as required). So possibly there needs to be a new option to control the logging of sub-millisecond timestamps.

**Comment by dmlloyd** [comment]
I think changing it to use `record.getInstant()` is the correct change. If anyone complains about too much precision, we could always introduce a time stamp truncation option.
